/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:/Users/User/Documents/coding/Portfolio Website/Portfolio/animated-portfolio/public/model/model.glb
*/

import React, { useEffect, useRef, useState } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";

const scaleValue = 1.15;

export function Avatar({
  cursorPos,
  currentAnimation,
  setCurrentAnimation,
  ...props
}) {
  const group = useRef();
  const { scene } = useGLTF("model/model.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { animations: standingIdleAnimation } = useFBX(
    "animations/Standing Idle.fbx"
  );
  const { animations: gettingUpAnimation } = useFBX(
    "animations/Getting Up.fbx"
  );
  const { animations: lyingDownAnimation } = useFBX(
    "animations/Lying Down.fbx"
  );

  //   console.log(standingIdleAnimation);

  standingIdleAnimation[0].name = "Standing";
  gettingUpAnimation[0].name = "GettingUp";
  lyingDownAnimation[0].name = "LyingDown";

  const { actions } = useAnimations(
    [standingIdleAnimation[0], gettingUpAnimation[0], lyingDownAnimation[0]],
    group
  );

  //cursor Follow logic
  useFrame(() => {
    if (currentAnimation === "Standing") {
      const target = new THREE.Vector3(cursorPos.x * 1, cursorPos.y * 1, 1);
      group.current.getObjectByName("Spine2").lookAt(target);
    }
  });

  useEffect(() => {
    actions[currentAnimation].reset().fadeIn(0.5).play();

    if (currentAnimation === "GettingUp") {
      setTimeout(() => {
        setCurrentAnimation("Standing");
      }, 7600);
    }
    return () => {
      actions[currentAnimation].reset().fadeOut(0.5);
    };
  }, [currentAnimation]);

  //   useEffect(() => {
  //     const action = actions[currentAnimation];
  //     console.log(action);
  //
  //     action.reset().fadeIn(0.5).play();
  //
  //     if (currentAnimation === "GettingUp") {
  //       action.clampWhenFinished = true; // Key line: Clamp to the last frame
  //       action.loop = THREE.LoopOnce; // Key line: Only play once
  //
  //       action.onLoop = () => {
  //         // Callback function for when the animation finishes
  //         setCurrentAnimation("Standing");
  //       };
  //     } else if (currentAnimation === "LyingDown") {
  //       action.clampWhenFinished = true; // Key line: Clamp to the last frame
  //       action.loop = THREE.LoopOnce; // Key line: Only play once
  //
  //       action.onLoop = () => {
  //         // Callback function for when the animation finishes
  //         setCurrentAnimation("Standing");
  //       };
  //     }
  //
  //     return () => {
  //       action.fadeOut(0.5);
  //       action.onLoop = null; // Important: Remove the callback to prevent it from firing after unmount
  //     };
  //   }, [currentAnimation]);

  return (
    <group
      {...props}
      ref={group}
      dispose={null}
      scale={[scaleValue, scaleValue, scaleValue]}
    >
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
        frustumCulled={false}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        frustumCulled={false}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        frustumCulled={false}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        frustumCulled={false}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
        frustumCulled={false}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        frustumCulled={false}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        frustumCulled={false}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        frustumCulled={false}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        frustumCulled={false}
      />
      <skinnedMesh
        name="Wolf3D_Beard"
        geometry={nodes.Wolf3D_Beard.geometry}
        material={materials.Wolf3D_Beard}
        skeleton={nodes.Wolf3D_Beard.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Beard.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Beard.morphTargetInfluences}
        frustumCulled={false}
      />
    </group>
  );
}

useGLTF.preload("model/model.glb");
